site_name: RISC-V Adventure Documentation

theme:
  name: material
  palette:
    # Dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
    # Light theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
  features:
    - navigation.tabs    # enable tabs in header

repo_url: https://github.com/GGalya1/riscv-architecture-educational-game
repo_name: RISC-V Adventure

nav:
  - Welcome: index.md
  - General:
    - Overview: general/overview.md
  - About project: about.md
  - Quickstart: quickstart.md
  - Concept: concept.md
  - Technology: tech-stack.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences