// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_steps = "CgkIjd7jxLoYEAIQAQ"; // <GPGSID>
        public const string achievement_i_wont_give_up = "CgkIjd7jxLoYEAIQBQ"; // <GPGSID>
        public const string achievement_perfect_try = "CgkIjd7jxLoYEAIQAw"; // <GPGSID>
        public const string achievement_true_hero = "CgkIjd7jxLoYEAIQAg"; // <GPGSID>
        public const string achievement_how_is_it_done = "CgkIjd7jxLoYEAIQBg"; // <GPGSID>
        public const string achievement_rollin_rollin_rollin = "CgkIjd7jxLoYEAIQBw"; // <GPGSID>
        public const string achievement_practice_makes_perfect = "CgkIjd7jxLoYEAIQBA"; // <GPGSID>

}

